function PhotoListCtrl($scope) 
{
	var commonWidth=100;
    $scope.photos = [
        {"file": "balloons.jpg",
         "description": "Palloncini colorati.",
		 "width": commonWidth,
         "tags": "palloncini giallo rosso verde colori"},
        {"file": "cards.jpg",
         "description": "Asso di cuori.",
		 "width": commonWidth,
         "tags": "carte da gioco asso di cuori"},
        {"file": "cardsJQ.jpg",
         "description": "Donna e Jack.",
		 "width": commonWidth,
         "tags": "carte da gioco donna jack picche cuori"},
        {"file": "chess.jpg",
         "description": "Scacchi allo specchio.",
		 "width": commonWidth,
         "tags": "scacchi specchio cavallo"},
        {"file": "interview.jpg",
         "description": "Colloquio di lavoro.",
		 "width": commonWidth,
         "tags": "colloquio di lavoro intervista"},
        {"file": "pianist.jpg",
         "description": "Suonare al pianoforte.",
		 "width": commonWidth,
         "tags": "pianoforte tasti musica"},
        {"file": "pound.jpg",
         "description": "Sterlina di ghiaccio.",
		 "width": commonWidth,
         "tags": "sterlina valuta ghiaccio"},
        {"file": "quick.jpg",
         "description": "Alta velocita' colorata.",
		 "width": commonWidth,
         "tags": "palline movimento colori rosso giallo verde rosa"},
        {"file": "stress.jpg",
         "description": "Via lo stress.",
		 "width": commonWidth,
         "tags": "stress gomma cancellare"},
        {"file": "watchmaker.jpg",
         "description": "L'orologiaio.",
		 "width": commonWidth,
         "tags": "orologio orologiaio occhi"}
      ];
}